# Project Euler: Problem 12
# Jonathan Kosasih

#The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
#
#1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
#
#Let us list the factors of the first seven triangle numbers:
#
# 1: 1
# 3: 1,3
# 6: 1,2,3,6
#10: 1,2,5,10
#15: 1,3,5,15
#21: 1,3,7,21
#28: 1,2,4,7,14,28
#We can see that 28 is the first triangle number to have over five divisors.
#
#What is the value of the first triangle number to have over five hundred divisors?
#------------------------------------------------------------------
import math
def answer():
    triangleNumber = 0
    divisors = 0
    index = 0
    while(divisors < 500):
        divisors = 0
        triangleNumber += index
        for i in range(1, int(math.sqrt(triangleNumber))):
            if(triangleNumber % i == 0):
                divisors += 1
        divisors *= 2
        index += 1
    return triangleNumber
print(str(answer()))
print("Test complete")