# Project Euler: Problem 45
# Jonathan Kosasih

#Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#
#Triangle        Tn=n(n+1)/2     1, 3, 6, 10, 15, ...
#Pentagonal      Pn=n(3n−1)/2        1, 5, 12, 22, 35, ...
#Hexagonal       Hn=n(2n−1)      1, 6, 15, 28, 45, ...
#It can be verified that T285 = P165 = H143 = 40755.
#
#Find the next triangle number that is also pentagonal and hexagonal.
#------------------------------------------------------------------
# wikipedia pentagonal numbers, check if n is a pentagonal number by if (1+(24n+1)^(1/2))/6 is an integer
def answer():
    i = 286
    j = 166
    k = 144
    while(True):
        tri = i*(i+1) // 2
        pen = j*(3*j - 1) // 2
        hex = k*(2*k - 1)
        minimum = min(tri, pen, hex)
        if(minimum == max(tri, pen, hex)):
            return tri
        if(minimum == tri):
            i += 1
        if(minimum == pen):
            j += 1
        if(minimum == hex):
            k += 1
    return ans
        
ans = answer()
print(str(ans))